name: “Compile & Run Tests"
on:
    push:
    pull_request:
jobs:
 runtests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            clean: true
        - name: checkout submodules 
          run: cd pose-bootcamp-code-quality-workshop/ & git submodule update --init
        - name: config cmake
          run: cmake -S . -B build
        - name: compile
          run: cmake --build build -j
        - name: runtest
          run: ./build/address_book_tests
