name: “Compile & Run Tests"
on:
    push:
    pull_request:
jobs:
 runtests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            clean: true
        - name: compile
          run: cmake --build build -j
        - name: runtest
          run: ./build/address_book_tests
