name: “Compile & Run Tests"
on:
    push:
    pull_request:
jobs:
 runtests:
    runs-on: ubuntu-latest
    steps:
     - name: compile
       run: cmake --build build -j
     - name: runtest
       run: ./build/address_book_tests
